version: "3"

tasks:
  setup:
    dotenv:
      - ./.env
    cmds:
      - defer: mix setup
      - "nix develop --no-write-lock-file $FLAKE_URL --command $SHELL"

  dev:
    cmds:
      - mix run ./lib/ghost_edit.exs

  prod:
    dotenv:
      - .env
    cmds:
      - defer: ./_build/prod/rel/ghostedit/bin/ghostedit start
      - mix release
